### ISSUE TITLE
Setting of avg_num_neighbors and Transferability over Dimension

### ISSUE THREAD

**Issue by blannek** [mariogeiger/nequip-jax#5]
I am found a poor transferability of my model over dimension, and I am trying to figure out why. One point comes to my mind is the avg_num_neighbors, by now it's set by the input dataset (similar to 'auto' in nequip pytorch), which varies with the dimension (the difference is small, though). Do I need to make the avg_num_neighbors all the same to improve the dimension transferability? If not, is there any suggestion?

**Comment by mariogeiger** [comment]
Yes I recommend to have it a constant.
